{
 "title": "External Secrets Operator",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "controller",
    "query": {
     "query": "label_values(controller_runtime_active_workers{service=~\".*external-secrets.*\"},  controller)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Admission Control Webhook", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "requests by path per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_webhook_requests_total{service=~\".*external-secrets.*\"}[1m])) by (webhook)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests in flight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(controller_runtime_webhook_requests_in_flight{service=~\".*external-secrets.*\"}) by (webhook)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests by code per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_webhook_requests_total{service=~\".*external-secrets.*\"}[1m])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "webhook latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_webhook_latency_seconds_bucket{service=~\".*external-secrets.*\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Controllers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "active workers by controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(controller_runtime_active_workers{service=~\".*external-secrets.*\",controller=~\"$controller\"}) by (controller)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "workqueue depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 18 },
   "targets": [
    {
     "expr": "sum(workqueue_depth{service=~\".*external-secrets.*\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API calls by provider",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(externalsecret_provider_api_calls_count{service=~\".*external-secrets.*\"}[1m])) by(provider, call, status)",
     "legendFormat": "{{provider}}/{{call}}={{status}}"
    }
   ]
  },
  {
   "title": "max concurrent: $controller",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3.4285714285714284, "x": 0, "y": 26 },
   "repeat": "controller",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(controller_runtime_max_concurrent_reconciles{service=~\".*external-secrets.*\",controller=\"$controller\"}) by (controller)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "reconcile rate per minute: $controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3.4285714285714284, "x": 0, "y": 32 },
   "repeat": "controller",
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"$controller\"}[1m])) by (result)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "reconcile time latency: $controller",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 3.4285714285714284, "x": 0, "y": 40 },
   "repeat": "controller",
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_time_seconds_bucket{service=~\".*external-secrets.*\",controller=~\"$controller\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}